import { OpenClawApiConfig, OpenClawLlmConfig, OpenClawPythonConfig, OpenClawSkillInput, ParsedSkill } from './types'

export interface AdaptedTool {
    name: string
    description: string
    iconSrc?: string
    schema: string
    func: string
}

const SAFE_INPUT_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/

function buildSchema(inputs: OpenClawSkillInput[]): string {
    const rows = inputs.map((inp, idx) => {
        if (!SAFE_INPUT_NAME.test(inp.property)) {
            throw new Error(`invalid input property name: ${inp.property}`)
        }
        return {
            id: idx + 1,
            property: inp.property,
            type: inp.type,
            description: inp.description ?? '',
            required: inp.required ?? false
        }
    })
    return JSON.stringify(rows)
}

/**
 * Walk a value tree, recursively replacing ${propName} placeholders with
 * a JS template-literal expression that resolves at sandbox runtime.
 * Returns a JS source snippet (string) representing the value.
 */
function literalize(value: unknown, propNames: Set<string>): string {
    if (value === null || value === undefined) return JSON.stringify(value)
    if (typeof value === 'number' || typeof value === 'boolean') return JSON.stringify(value)
    if (typeof value === 'string') return interpolateString(value, propNames)
    if (Array.isArray(value)) return '[' + value.map((v) => literalize(v, propNames)).join(',') + ']'
    if (typeof value === 'object') {
        const parts = Object.entries(value as Record<string, unknown>).map(([k, v]) => JSON.stringify(k) + ':' + literalize(v, propNames))
        return '{' + parts.join(',') + '}'
    }
    return JSON.stringify(value)
}

function interpolateString(str: string, propNames: Set<string>): string {
    // Convert "hello ${city}" → `hello ${$city}` (template literal)
    // ${vars.X} → ${$vars.X}; unknown ${...} left as literal text.
    const segments: string[] = []
    let lastIdx = 0
    const re = /\$\{([^}]+)\}/g
    let match: RegExpExecArray | null
    while ((match = re.exec(str)) !== null) {
        segments.push(escapeForTemplateLiteral(str.slice(lastIdx, match.index)))
        const expr = match[1].trim()
        if (propNames.has(expr)) {
            segments.push('${$' + expr + '}')
        } else if (expr.startsWith('vars.')) {
            segments.push('${$vars.' + expr.slice(5).replace(/[^A-Za-z0-9_.]/g, '') + '}')
        } else {
            // unrecognized — keep as plain text
            segments.push(escapeForTemplateLiteral('${' + expr + '}'))
        }
        lastIdx = re.lastIndex
    }
    segments.push(escapeForTemplateLiteral(str.slice(lastIdx)))
    return '`' + segments.join('') + '`'
}

function escapeForTemplateLiteral(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

function generateApiFunc(config: OpenClawApiConfig, inputs: OpenClawSkillInput[]): string {
    const props = new Set(inputs.map((i) => i.property))
    const url = literalize(config.url, props)
    const method = JSON.stringify((config.method || 'GET').toUpperCase())
    const headers = literalize(config.headers || { 'Content-Type': 'application/json' }, props)
    const hasBody = config.body !== undefined
    const bodyExpr = hasBody ? literalize(config.body, props) : 'undefined'

    return `// Auto-generated by OpenClaw skill adapter (api)
const url = ${url};
const method = ${method};
const headers = ${headers};
const body = ${bodyExpr};
const init = { method, headers };
if (method !== 'GET' && method !== 'HEAD' && body !== undefined) {
    init.body = typeof body === 'string' ? body : JSON.stringify(body);
}
const response = await fetch(url, init);
const text = await response.text();
return text;`
}

function generateLlmFunc(config: OpenClawLlmConfig, inputs: OpenClawSkillInput[]): string {
    const props = new Set(inputs.map((i) => i.property))
    const endpoint = JSON.stringify(config.endpoint)
    const model = JSON.stringify(config.model || 'gpt-4o-mini')
    const apiKeyVar = JSON.stringify(config.apiKeyVar || 'OPENAI_API_KEY')
    const promptTemplate = literalize(config.promptTemplate || '', props)

    return `// Auto-generated by OpenClaw skill adapter (llm)
const endpoint = ${endpoint};
const model = ${model};
const apiKey = $vars[${apiKeyVar}];
if (!apiKey) {
    throw new Error('Missing variable: ' + ${apiKeyVar});
}
const prompt = ${promptTemplate};
const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + apiKey
    },
    body: JSON.stringify({
        model,
        messages: [{ role: 'user', content: prompt }]
    })
});
const data = await response.json();
return data?.choices?.[0]?.message?.content ?? JSON.stringify(data);`
}

function generatePythonFunc(config: OpenClawPythonConfig, inputs: OpenClawSkillInput[], pythonSource: string): string {
    const apiKeyVar = JSON.stringify(config.e2bApiKeyVar || 'E2B_APIKEY')
    const timeoutMs = typeof config.timeout === 'number' ? Math.floor(config.timeout) : 60000
    // Build the JS expression that constructs the per-call inputs object at runtime.
    // Each input.property is sandbox-injected as $<name>; collect them into one object.
    const inputsObjLiteral =
        '{' +
        inputs
            .map((inp) => {
                const key = JSON.stringify(inp.property)
                const ref = '$' + inp.property
                return `${key}: typeof ${ref} !== 'undefined' ? ${ref} : null`
            })
            .join(', ') +
        '}'
    // The user's Python source is fixed at adapter time; embed it as a JS string literal.
    const pyBodyLiteral = JSON.stringify(pythonSource)

    return `// Auto-generated by OpenClaw skill adapter (python via E2B)
const { Sandbox } = require('@e2b/code-interpreter');
const apiKey = $vars[${apiKeyVar}];
if (!apiKey) {
    throw new Error('Python skill requires variable: ' + ${apiKeyVar});
}
const __args = ${inputsObjLiteral};
// Inject inputs as Python globals via json.loads of a JS-stringified JSON literal
// (JSON string syntax is also a valid Python string literal, so double-stringify is safe).
const __pyHeader = 'import json\\n__inputs = json.loads(' + JSON.stringify(JSON.stringify(__args)) + ')\\n' +
    Object.keys(__args).map(function (k) { return k + ' = __inputs[' + JSON.stringify(k) + ']'; }).join('\\n') + '\\n';
const __pyBody = ${pyBodyLiteral};
const __code = __pyHeader + '\\n' + __pyBody;
const sbx = await Sandbox.create({ apiKey, timeoutMs: ${timeoutMs} });
try {
    const exec = await sbx.runCode(__code, { language: 'python' });
    if (exec.error) {
        throw new Error('Python error: ' + (exec.error.value || exec.error.name));
    }
    if (exec.text) return exec.text;
    if (exec.logs && exec.logs.stdout && exec.logs.stdout.length) return exec.logs.stdout.join('');
    return '';
} finally {
    try { await sbx.kill(); } catch (e) { /* ignore */ }
}`
}

export function adaptSkillToTool(parsed: ParsedSkill): AdaptedTool {
    const { manifest, entryContent } = parsed
    const schema = buildSchema(manifest.inputs)

    let func: string
    switch (manifest.type) {
        case 'api': {
            const cfg = (manifest.config || {}) as OpenClawApiConfig
            if (!cfg.url) throw new Error('api skill requires config.url')
            func = generateApiFunc(cfg, manifest.inputs)
            break
        }
        case 'llm': {
            const cfg = (manifest.config || {}) as OpenClawLlmConfig
            if (!cfg.endpoint) throw new Error('llm skill requires config.endpoint')
            func = generateLlmFunc(cfg, manifest.inputs)
            break
        }
        case 'code': {
            if (!entryContent) throw new Error('code skill requires entry file or entryContent')
            func = entryContent
            break
        }
        case 'python': {
            if (!entryContent) throw new Error('python skill requires entry file (.py) or entryContent')
            const cfg = (manifest.config || {}) as OpenClawPythonConfig
            func = generatePythonFunc(cfg, manifest.inputs, entryContent)
            break
        }
        default:
            throw new Error(`unsupported skill type: ${(manifest as { type: string }).type}`)
    }

    // Prepend Phase 3 metadata as a JSON comment so SkillAutoBinder can detect it
    const phase3 = {
        personalityProfile: manifest.personalityProfile,
        minLevel: manifest.minLevel,
        boundIntents: manifest.boundIntents
    }
    const hasPh3 = manifest.personalityProfile || manifest.minLevel !== undefined || manifest.boundIntents
    const funcWithMeta = hasPh3 ? `// @openclaw-meta:${JSON.stringify(phase3)}\n${func}` : func

    return {
        name: manifest.name,
        description: manifest.description,
        iconSrc: manifest.iconUrl,
        schema,
        func: funcWithMeta
    }
}
