import { OpenClawApiConfig, OpenClawLlmConfig, OpenClawSkillInput, ParsedSkill } from './types'

export interface AdaptedTool {
    name: string
    description: string
    iconSrc?: string
    schema: string
    func: string
}

const SAFE_INPUT_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/

function buildSchema(inputs: OpenClawSkillInput[]): string {
    const rows = inputs.map((inp, idx) => {
        if (!SAFE_INPUT_NAME.test(inp.property)) {
            throw new Error(`invalid input property name: ${inp.property}`)
        }
        return {
            id: idx + 1,
            property: inp.property,
            type: inp.type,
            description: inp.description ?? '',
            required: inp.required ?? false
        }
    })
    return JSON.stringify(rows)
}

/**
 * Walk a value tree, recursively replacing ${propName} placeholders with
 * a JS template-literal expression that resolves at sandbox runtime.
 * Returns a JS source snippet (string) representing the value.
 */
function literalize(value: unknown, propNames: Set<string>): string {
    if (value === null || value === undefined) return JSON.stringify(value)
    if (typeof value === 'number' || typeof value === 'boolean') return JSON.stringify(value)
    if (typeof value === 'string') return interpolateString(value, propNames)
    if (Array.isArray(value)) return '[' + value.map((v) => literalize(v, propNames)).join(',') + ']'
    if (typeof value === 'object') {
        const parts = Object.entries(value as Record<string, unknown>).map(([k, v]) => JSON.stringify(k) + ':' + literalize(v, propNames))
        return '{' + parts.join(',') + '}'
    }
    return JSON.stringify(value)
}

function interpolateString(str: string, propNames: Set<string>): string {
    // Convert "hello ${city}" → `hello ${$city}` (template literal)
    // ${vars.X} → ${$vars.X}; unknown ${...} left as literal text.
    const segments: string[] = []
    let lastIdx = 0
    const re = /\$\{([^}]+)\}/g
    let match: RegExpExecArray | null
    while ((match = re.exec(str)) !== null) {
        segments.push(escapeForTemplateLiteral(str.slice(lastIdx, match.index)))
        const expr = match[1].trim()
        if (propNames.has(expr)) {
            segments.push('${$' + expr + '}')
        } else if (expr.startsWith('vars.')) {
            segments.push('${$vars.' + expr.slice(5).replace(/[^A-Za-z0-9_.]/g, '') + '}')
        } else {
            // unrecognized — keep as plain text
            segments.push(escapeForTemplateLiteral('${' + expr + '}'))
        }
        lastIdx = re.lastIndex
    }
    segments.push(escapeForTemplateLiteral(str.slice(lastIdx)))
    return '`' + segments.join('') + '`'
}

function escapeForTemplateLiteral(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

function generateApiFunc(config: OpenClawApiConfig, inputs: OpenClawSkillInput[]): string {
    const props = new Set(inputs.map((i) => i.property))
    const url = literalize(config.url, props)
    const method = JSON.stringify((config.method || 'GET').toUpperCase())
    const headers = literalize(config.headers || { 'Content-Type': 'application/json' }, props)
    const hasBody = config.body !== undefined
    const bodyExpr = hasBody ? literalize(config.body, props) : 'undefined'

    return `// Auto-generated by OpenClaw skill adapter (api)
const url = ${url};
const method = ${method};
const headers = ${headers};
const body = ${bodyExpr};
const init = { method, headers };
if (method !== 'GET' && method !== 'HEAD' && body !== undefined) {
    init.body = typeof body === 'string' ? body : JSON.stringify(body);
}
const response = await fetch(url, init);
const text = await response.text();
return text;`
}

function generateLlmFunc(config: OpenClawLlmConfig, inputs: OpenClawSkillInput[]): string {
    const props = new Set(inputs.map((i) => i.property))
    const endpoint = JSON.stringify(config.endpoint)
    const model = JSON.stringify(config.model || 'gpt-4o-mini')
    const apiKeyVar = JSON.stringify(config.apiKeyVar || 'OPENAI_API_KEY')
    const promptTemplate = literalize(config.promptTemplate || '', props)

    return `// Auto-generated by OpenClaw skill adapter (llm)
const endpoint = ${endpoint};
const model = ${model};
const apiKey = $vars[${apiKeyVar}];
if (!apiKey) {
    throw new Error('Missing variable: ' + ${apiKeyVar});
}
const prompt = ${promptTemplate};
const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + apiKey
    },
    body: JSON.stringify({
        model,
        messages: [{ role: 'user', content: prompt }]
    })
});
const data = await response.json();
return data?.choices?.[0]?.message?.content ?? JSON.stringify(data);`
}

export function adaptSkillToTool(parsed: ParsedSkill): AdaptedTool {
    const { manifest, entryContent } = parsed
    const schema = buildSchema(manifest.inputs)

    let func: string
    switch (manifest.type) {
        case 'api': {
            const cfg = (manifest.config || {}) as OpenClawApiConfig
            if (!cfg.url) throw new Error('api skill requires config.url')
            func = generateApiFunc(cfg, manifest.inputs)
            break
        }
        case 'llm': {
            const cfg = (manifest.config || {}) as OpenClawLlmConfig
            if (!cfg.endpoint) throw new Error('llm skill requires config.endpoint')
            func = generateLlmFunc(cfg, manifest.inputs)
            break
        }
        case 'code': {
            if (!entryContent) throw new Error('code skill requires entry file or entryContent')
            func = entryContent
            break
        }
        default:
            throw new Error(`unsupported skill type: ${(manifest as { type: string }).type}`)
    }

    return {
        name: manifest.name,
        description: manifest.description,
        iconSrc: manifest.iconUrl,
        schema,
        func
    }
}
